const About = () =>{
    return(
        <div>
           Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam in nisl ut lacus malesuada commodo convallis nec diam. Ut commodo suscipit maximus. Nulla et mollis ipsum. Nunc vestibulum turpis ac efficitur tristique. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam in interdum turpis. In dapibus aliquam turpis, id lobortis dui ornare vitae. Suspendisse potenti. Pellentesque nec malesuada orci. Sed vel orci et tellus fermentum vestibulum.

Maecenas varius tempor pharetra. Ut eu commodo eros, nec commodo massa. Praesent vel maximus magna, imperdiet volutpat quam. Sed ornare iaculis lacus, id tempor ante. Sed elementum in turpis vel laoreet. Aliquam erat volutpat. Phasellus blandit dui vel libero euismod feugiat. Nam hendrerit ipsum eu purus feugiat tempus.

Curabitur et nulla neque. Nunc hendrerit dui in risus scelerisque ullamcorper. Etiam justo felis, facilisis eu libero quis, hendrerit ultricies felis. Proin mi dui, lobortis sed dolor sit amet, mattis mollis sem. Quisque sit amet pharetra diam. Curabitur sollicitudin dui velit, vel tempor eros scelerisque eleifend. Phasellus nec arcu libero. Duis egestas arcu risus, at venenatis mi facilisis venenatis.

Praesent feugiat nisi sit amet eros viverra semper. Sed risus eros, accumsan eget gravida eget, fringilla nec turpis. Integer eu nunc imperdiet, laoreet velit vel, tempor enim. Duis egestas est id ex consectetur semper. Cras eget leo vel erat consectetur venenatis. In tempor lorem non lectus tristique, quis euismod ante interdum. Phasellus scelerisque gravida mauris a porttitor. Aliquam sed lorem fermentum, aliquet turpis a, egestas libero. Curabitur convallis sapien odio, non elementum quam volutpat id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus sed neque convallis, aliquam metus a, fringilla urna. Nam scelerisque arcu a diam placerat pellentesque. Suspendisse non justo at turpis facilisis interdum. Donec sollicitudin volutpat neque viverra tempus. Nulla fringilla enim quis egestas convallis.

Cras non ligula tempor, dictum ante vel, sagittis dolor. Proin ac tellus placerat, fermentum lorem nec, ullamcorper velit. Donec dignissim justo et cursus semper. Aliquam lorem ex, eleifend nec ullamcorper eget, ultrices quis odio. Sed sed odio vitae lorem sagittis scelerisque. Praesent quis ornare metus. Proin laoreet sapien et dapibus sollicitudin. Nunc pulvinar bibendum dolor, sed lobortis risus gravida bibendum.

Integer eget dictum mauris. Ut rhoncus consequat libero vel consectetur. Donec sit amet semper sapien. Sed suscipit quis elit at blandit. Phasellus eleifend cursus faucibus. Praesent et semper quam, vel dignissim enim. Pellentesque finibus aliquam ipsum eget gravida. Nam fringilla augue lacus, id lacinia lacus eleifend imperdiet. Etiam mollis non ligula a tempus. Donec pulvinar at augue nec pulvinar. Donec magna dolor, aliquam vel massa in, feugiat finibus lacus. Fusce quis semper leo. Integer gravida id neque pharetra lobortis. Phasellus consectetur bibendum euismod. Nam condimentum nunc turpis, sed posuere lorem commodo tincidunt.

Ut rhoncus eu velit vel pulvinar. Donec in nisl vitae velit convallis pulvinar. Ut congue imperdiet dapibus. Vestibulum vehicula, purus sit amet condimentum imperdiet, justo libero aliquam libero, quis volutpat sapien lacus vitae augue. Morbi maximus nisl neque, et pulvinar lectus vestibulum eu. Sed tristique ac purus eu sagittis. Duis lobortis, massa et consequat eleifend, metus nisl tempor augue, ut elementum eros metus eget dui. Fusce dolor leo, convallis sit amet venenatis ut, facilisis eu justo.

Nunc euismod ultricies malesuada. Duis consectetur magna enim, eu sodales nulla facilisis id. Nulla et elit felis. Nam non lorem sed metus consectetur viverra fringilla facilisis dolor. Integer lacinia ligula vitae mauris laoreet luctus. Etiam aliquam, lectus lacinia sollicitudin posuere, ligula arcu mollis nibh, quis blandit nunc diam nec felis. Ut nec magna velit. Sed tincidunt mattis enim.

Vivamus eget pretium magna, eu tincidunt leo. Nullam ac fringilla mi, vel laoreet libero. Nulla libero ipsum, vehicula eu urna egestas, tincidunt imperdiet massa. Duis id accumsan risus. Suspendisse risus ligula, faucibus sit amet leo eget, varius dictum nunc. Maecenas in erat eget massa lobortis mollis sit amet non tellus. Quisque faucibus sagittis iaculis. Duis nec faucibus justo, in facilisis diam.

Nulla iaculis quam ut nisl molestie venenatis. Donec ut erat lacus. Pellentesque mattis tellus a enim tincidunt mattis. Fusce massa nulla, pharetra quis nisi nec, blandit convallis odio. Aliquam consequat ante eget sem tempus pharetra. Nulla iaculis aliquet blandit. Curabitur interdum aliquam arcu, convallis mollis arcu feugiat quis. Phasellus nec orci hendrerit, malesuada leo ut, vehicula eros.

Duis et ante purus. Quisque porta arcu leo, non condimentum justo posuere vulputate. Etiam vel nibh sapien. Quisque imperdiet dolor vel nisl sagittis varius eu id leo. Quisque porta eros et auctor elementum. Quisque vestibulum metus ac massa sodales placerat. Vestibulum dolor nunc, egestas eget sapien vitae, vestibulum fringilla elit. Morbi diam quam, laoreet id quam ut, dictum mollis nulla. Nunc sagittis pellentesque lacinia. Phasellus non sem eget erat iaculis sodales. Maecenas interdum nulla id neque volutpat sodales. Praesent a scelerisque sem. Integer lobortis semper purus at rhoncus. Vestibulum efficitur metus et nunc fermentum placerat. Aliquam erat volutpat.

Fusce vestibulum, felis dictum bibendum viverra, ipsum mauris cursus erat, a tristique nunc purus eu mauris. Pellentesque sit amet nisl ut urna blandit cursus et vitae lectus. Cras molestie nisl viverra velit sagittis ullamcorper. Curabitur quis nisi feugiat, tincidunt urna nec, mollis ipsum. Suspendisse vel auctor dolor. Praesent molestie et ligula sed faucibus. Curabitur pretium, orci iaculis rutrum egestas, odio nulla euismod justo, vitae dictum tellus augue in magna. Maecenas maximus augue semper ipsum rhoncus malesuada. Vivamus efficitur ullamcorper ante, consequat accumsan est bibendum at. Aliquam iaculis pharetra orci eu mattis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Ut eget viverra nunc. Nam consequat, magna quis dignissim tristique, magna libero cursus elit, et accumsan nisl mauris in orci. Maecenas vulputate lacus vitae felis imperdiet, nec ullamcorper lectus sollicitudin. Donec euismod molestie luctus. Maecenas tristique aliquet purus in rutrum. Sed hendrerit in orci a pulvinar. Sed vel quam sed mauris tempor placerat et at lacus. Aenean tempor, lorem in tempus tincidunt, augue augue egestas nibh, a cursus sapien magna ut magna. Nam scelerisque purus eu fermentum rutrum. Mauris sollicitudin, leo quis dapibus pretium, ipsum leo congue justo, nec sagittis ante mauris et erat. Vivamus turpis urna, mattis eget dignissim non, consequat eu leo. Cras finibus lectus id augue aliquet semper. Cras fermentum mi velit, a ultrices nisl volutpat id.

Proin auctor imperdiet quam, ac consequat felis. Integer ultricies volutpat semper. Donec eget ullamcorper magna. Duis pretium, mauris nec euismod dignissim, libero erat consectetur justo, eget ullamcorper ipsum velit id arcu. Mauris eget aliquam arcu. Etiam consequat tincidunt ex et viverra. Aenean sit amet magna a elit euismod pellentesque nec nec nulla. Aenean ac varius orci. Praesent hendrerit nibh quis mauris tristique porttitor. Nullam eget sem leo. Etiam dui mauris, molestie ac efficitur vel, ornare et eros. Ut a tempus enim. Maecenas elementum, libero eget tincidunt ultricies, ipsum lectus fringilla metus, quis facilisis enim purus et metus. Morbi maximus varius risus eget blandit. Aliquam arcu risus, lobortis ut augue non, mollis interdum tellus.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi felis felis, lobortis in nisi at, pretium lacinia felis. Nulla suscipit elit ut suscipit dapibus. Duis ultrices tortor non eros lobortis ullamcorper. In sem neque, gravida a elementum quis, vestibulum rhoncus magna. Suspendisse iaculis dolor sed urna pretium, sit amet accumsan libero hendrerit. Donec a gravida mauris. Mauris nisi nibh, tempor sit amet nulla in, pellentesque facilisis leo. Fusce volutpat purus odio, quis dictum mauris scelerisque sed. Pellentesque vehicula erat ac tellus vestibulum, tincidunt pharetra sapien placerat.

Maecenas id odio lacinia, pulvinar tellus a, rutrum dui. Integer sit amet libero eget nibh aliquam molestie sit amet vel urna. Vivamus sagittis, sem ut malesuada suscipit, eros metus volutpat est, non rhoncus massa lectus quis nisl. Aenean tempus, nibh vel dapibus vehicula, quam elit pellentesque neque, a sodales erat tortor sed libero. Duis vel sodales neque, sit amet volutpat ipsum. Vivamus at semper tellus. Duis cursus dui et lectus finibus, id tristique felis facilisis. Nulla malesuada urna venenatis urna scelerisque, a sollicitudin velit condimentum. Aenean blandit nibh diam.

In lacinia gravida bibendum. In vehicula libero vel tellus porttitor, eget venenatis massa dictum. Nullam in scelerisque diam, quis hendrerit lectus. Vestibulum eu imperdiet est. Aenean viverra purus eget odio vulputate, quis tempor purus lobortis. Aliquam ex eros, mattis sit amet turpis at, congue tincidunt purus. Quisque et felis gravida, malesuada risus vitae, sollicitudin magna. Sed vehicula risus bibendum aliquet vehicula.

Duis porttitor quam a ligula consequat maximus. Duis elit ex, commodo eu luctus eget, vestibulum non tortor. Proin euismod felis et eros mattis pharetra. Nullam felis augue, consequat rutrum tortor bibendum, faucibus aliquam nibh. Integer feugiat ipsum vel libero tempor convallis. Donec dictum eu risus ac varius. Nunc a sagittis libero. Proin vulputate luctus velit. Pellentesque bibendum eu turpis eu sagittis. Aliquam bibendum ultrices ultrices. Nulla odio velit, iaculis sed massa vel, ullamcorper ornare tortor. Sed nec maximus erat. Suspendisse quis purus eget neque tincidunt posuere nec ac lacus. Sed maximus enim ac enim aliquet aliquam. Nam a tincidunt nulla, ut fringilla nulla. Proin sed enim lorem.

Donec nunc purus, commodo non sem eget, elementum vehicula lectus. Vivamus tincidunt fringilla orci interdum rutrum. Vivamus ut velit mollis, pretium eros vel, mollis ipsum. Vestibulum nec massa varius, pellentesque lectus eu, auctor dolor. Sed ut feugiat lorem. Aliquam tortor purus, egestas vel enim sit amet, iaculis elementum nisi. Morbi et auctor leo. Duis ligula ex, auctor a leo ullamcorper, mollis accumsan mauris. Curabitur consectetur erat quis pulvinar commodo. Quisque eget risus eros. Duis nec tristique leo. Suspendisse potenti. Nunc in tempus purus. Cras vel hendrerit dolor. Donec eu metus eu urna vulputate semper vitae posuere arcu. Nullam et sagittis lectus.

Ut nec gravida justo, a laoreet felis. Maecenas a luctus orci. Ut rhoncus risus bibendum nulla fringilla volutpat. Vivamus sem elit, pharetra ac efficitur sit amet, placerat in ante. Sed iaculis dolor in nunc efficitur tincidunt. Aliquam massa lorem, fringilla vel semper non, ullamcorper nec mi. Morbi volutpat maximus turpis vitae ornare. Sed nibh mi, mollis non gravida id, gravida a lectus. Praesent ut libero ante. Maecenas ut metus eu velit condimentum aliquet. Curabitur dapibus rutrum odio, ut molestie mauris consectetur quis. Etiam justo massa, auctor fermentum pharetra non, vehicula sed nunc. Praesent vitae pharetra ante, nec porttitor erat. Aenean volutpat lacus non congue eleifend. Sed iaculis magna eget urna imperdiet, sed consequat nunc volutpat. Nulla euismod ante sed diam pulvinar pulvinar.
        </div>
    )
}

export default About;
//lazy laod then compoent. All component won't be downloaded at the same time. Dependign on the route it will download
// the component required. Fast the initial load
// goto -lipsum.com